version: 2.1
workflows:
  testing:
    jobs:
      - build_odenne
      - start_odenne:
          requires:
            - build_odenne
jobs:
  runner-test:
    machine: true
    resource_class: testservergames/vrpg
    steps:
      - run: echo "Hi I'm on Runners!"
  build_odenne:
    machine: true
    resource_class: testservergames/vrpg
    steps:
      - run: /Users/mbilgehanertan/Documents/VRPG/odenne/build.sh
      - run: echo "Build success"
  start_odenne:
    machine: true
    resource_class: testservergames/vrpg
    steps:
      - run: sudo /Users/mbilgehanertan/Documents/VRPG/odenne/start.sh
      - run: echo "Start Success!"