version: 2.1
workflows:
  testing:
    jobs:
      - build_odenne
      - start_odenne:
          requires:
            - build_odenne
jobs:
  runner-test:
    machine: true
    resource_class: testservergames/vrpg
    steps:
      - run: echo "Hi I'm on Runners!"
  build_odenne:
    machine: true
    working_directory: /Users/mbilgehanertan/Documents/VRPG/odenne
    resource_class: testservergames/vrpg
    steps:
      - run: 
          name: "Removing old dockers"
          command: "docker rm -f odenne_worker_1 odenne_worker_2"
      - run: 
          name: Building odenne...
          command: docker build -t odenne:1.0.2 .
      - run: echo "Build success"
  start_odenne:
    machine: true
    working_directory: /Users/mbilgehanertan/Documents/VRPG/odenne
    resource_class: testservergames/vrpg
    steps:
      - run: 
          name: Starting Odenne Worker 1
          command: docker run -d -p 3101:4999 --name odenne_worker_1 odenne:1.0.2 .
      - run: 
          name: Starting Odenne Worker 2
          command: docker run -d -p 3102:4999 --name odenne_worker_2 odenne:1.0.2 .
      - run: echo "Start success!"